name: qr_code
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  get: ^4.5.0
  open_file_plus: ^3.4.0
  path_provider: ^2.1.0
  pdf: ^3.3.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
